### PR TITLE
TEST

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by isuruf** [comment]
@conda-forge-admin, please lint

**Comment by ocefpaf** [comment]
@conda-forge-admin, please bring me :coffee: 

@isuruf I guess it is broken, still waiting for my coffee :wink: 

Jokes aside this is an awesome addition to our ecosystem! Thanks a lot for implementing this!

**Comment by isuruf** [comment]
@conda-forge-admin, please lint

**Comment by isuruf** [comment]
Hmm, re-linting seems to be broken

**Comment by jakirkham** [comment]
Commented on your original PR to note the issue.

**Comment by isuruf** [comment]
@conda-forge-admin, please lint

**Pull request closed without merging**
